openapi: 3.0.3
info:
  title: Wallet management
  version: 1.0.0
  description: STD22026_STD22020
servers:
  - url: https://wallet.com
tags:
  - name: Accounts
    description: Operations related to accounts
  - name: Transactions
    description: Operations related to transactions
  - name: Currencies
    description: Operations related to currencies
paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Retrieve the list of accounts
      description: The returne account all ordered
      operationId: getAccount
      responses:
        200:
          $ref: "#/components/responses/AccountList_200"
        400:
          $ref: "#/components/responses/BadRequest_400"
        403:
          $ref: "#/components/responses/ForbiddenRequest_403"
        500:
          $ref: "#/components/responses/ErrorRequest_500"
    post:
      summary: Add a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          $ref: "#/components/responses/AccountList_200"
        400:
          $ref: "#/components/responses/BadRequest_400"
        403:
          $ref: "#/components/responses/ForbiddenRequest_403"
        500:
          $ref: "#/components/responses/ErrorRequest_500"

  /accounts/{accountId}:
    get:
      tags:
        - Accounts
      summary: Retrieve details of an account
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: integer
      responses:
        200:
          $ref: "#/components/responses/AccountList_200"
        400:
          $ref: "#/components/responses/BadRequest_400"
        403:
          $ref: "#/components/responses/ForbiddenRequest_403"
        500:
          $ref: "#/components/responses/ErrorRequest_500"
    put:
      tags:
        - Accounts
      summary: Modify an existing account
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          $ref: "#/components/responses/AccountList_200"
        400:
          $ref: "#/components/responses/BadRequest_400"
        403:
          $ref: "#/components/responses/ForbiddenRequest_403"
        500:
          $ref: "#/components/responses/ErrorRequest_500"

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        currency:
          type: array
          items:
            $ref: "#/components/schemas/Currency"

    Transaction:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: number
        date:
          type: string
          format: date
        description:
          type: string

    Currency:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        symbol:
          type: string

    ResponseStatus:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: OK
    ResponseBodyTemplate:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'
        body:
          type: object

    BadRequestBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 400
          message: BAD REQUEST
        body: { }


    ForbiddenRequest:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 403
          message: FORBIDDEN
        body: { }

    ServerErrorRequest:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 500
          message: Internal servor error
        body: { }
    AccountListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Account'
    TransactionListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
    CurrencyListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Currency'

  responses:
    AccountList_200:
      description: List of accounts
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountListBody'
    TransactionList_200:
      description: List of transactions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransactionListBody'
    CurrencyList_200:
      description: List of currencies
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrencyListBody'

    BadRequest_400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
    ForbiddenRequest_403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenRequest'
    ErrorRequest_500:
      description: Error request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorRequest'